#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing relay go routines
graph_vlabel number of go routines
graph_category network
strelaysrv_status_gor.label routines 
EOM
        exit 0;;
esac

printf "strelaysrv_status_gor.value "
curl -s http://$STR_HOST:$STR_PORT/status | jq '.goNumRoutine'
