#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing relay transfer rate
graph_category network
graph_vlabel bps
graph_args --base 1000
strelaysrv_status_transfer.label bps
strelaysrv_status_transfer.cdef strelaysrv_status_transfer,8000,*
EOM
        exit 0;;
esac

printf "strelaysrv_status_transfer.value "
curl -s http://$STR_HOST:$STR_PORT/status | jq '.kbps10s1m5m15m30m60m[2] '
