#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing relay numbers
graph_category network
graph_vlabel numbers
strelaysrv_status_num_sessions.label sessions
strelaysrv_status_num_connections.label connections
strelaysrv_status_num_pending.label pending session keys
strelaysrv_status_num_proxies.label proxies
EOM
        exit 0;;
esac

NS=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numActiveSessions ')
NC=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numConnections ')
NK=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numPendingSessionKeys ')
NP=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numProxies ')
printf "strelaysrv_status_num_sessions.value $NS\nstrelaysrv_status_num_connections.value $NC\nstrelaysrv_status_num_pending.value $NK\nstrelaysrv_status_num_proxies.value $NP\n"

