#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing relay uptime
graph_vlabel uptime in seconds
graph_category syncthing
strelaysrv_status_uptime.label uptime
EOM
        exit 0;;
esac

printf "strelaysrv_status_uptime.value "
curl -s http://$STR_HOST:$STR_PORT/status | jq '.uptimeSeconds' 
