#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing uptime
graph_vlabel uptime in seconds
graph_category network
syncthing_system_status_uptime.label uptime
EOM
        exit 0;;
esac

printf "syncthing_system_status_uptime.value "
curl -s -X GET -H "X-API-Key: $ST_APIKEY" $ST_PROTO://$ST_HOST:$ST_PORT/rest/system/status | jq '.uptime' 
