#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing go routines
graph_vlabel number of go routines
graph_category syncthing
syncthing_system_status_gor.label routines 
EOM
        exit 0;;
esac

printf "syncthing_system_status_gor.value "
curl -s -X GET -H "X-API-Key: $ST_APIKEY" $ST_PROTO://$ST_HOST:$ST_PORT/rest/system/status | jq '.goroutines'
