#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing total transfer 
graph_category network
graph_order syncthing_system_connections_transfer_down syncthing_system_connections_transfer_up
graph_args --base 1000
graph_vlabel bits in (-) / out (+) per ${graph_period}
syncthing_system_connections_transfer_down.label received
syncthing_system_connections_transfer_down.type COUNTER
syncthing_system_connections_transfer_down.graph no
syncthing_system_connections_transfer_down.cdef syncthing_system_connections_transfer_down,8,*
syncthing_system_connections_transfer_up.label bps
syncthing_system_connections_transfer_up.type COUNTER
syncthing_system_connections_transfer_up.negative syncthing_system_connections_transfer_down
syncthing_system_connections_transfer_up.cdef syncthing_system_connections_transfer_up,8,*
EOM
        exit 0;;
esac

IBT=$(curl -s -X GET -H "X-API-Key: $ST_APIKEY" $ST_PROTO://$ST_HOST:$ST_PORT/rest/system/connections | jq '.total | .inBytesTotal')
OBT=$(curl -s -X GET -H "X-API-Key: $ST_APIKEY" $ST_PROTO://$ST_HOST:$ST_PORT/rest/system/connections | jq '.total | .outBytesTotal')
printf "syncthing_system_connections_transfer_up.value $IBT\nsyncthing_system_connections_transfer_down.value $OBT\n"

