#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Syncthing cpu usage
graph_vlabel %
graph_category syncthing
syncthing_system_status_cpu.label cpu
EOM
        exit 0;;
esac

printf "syncthing_system_status_cpu.value "
curl -s -X GET -H "X-API-Key: $ST_APIKEY" $ST_PROTO://$ST_HOST:$ST_PORT/rest/system/status | jq '.cpuPercent'
